### ISSUE TITLE
大佬是否考虑增加帖子点赞和点赞用户列表功能

### ISSUE THREAD

**Issue by Yakumo-Yukari** [coder279/BBS#3]
![2020-11-24 151640](https://user-images.githubusercontent.com/12076232/100060941-41c77800-2e68-11eb-80d6-ececb39eeffc.png)

类似图片中这种功能

**Comment by coder279** [comment]
有赞成和反对

**Comment by Yakumo-Yukari** [comment]
> 有赞成和反对

好的
